ALTER TABLE [dbo].[JobHistory] DROP CONSTRAINT [FK_JobHistory_Company_CompanyID];
ALTER TABLE [dbo].[JobHistory] DROP CONSTRAINT [FK_JobHistory_Position_PositionID];
ALTER TABLE [dbo].[JobHistory] DROP CONSTRAINT [FK_JobHistory_Project_ProjectID];
ALTER TABLE [dbo].[ProjectSkill] DROP CONSTRAINT [FK_ProjectSkill_ProjectID];
ALTER TABLE [dbo].[ProjectSkill] DROP CONSTRAINT [FK_ProjectSkill_SkillID];
ALTER TABLE [dbo].[JobHistory] DROP CONSTRAINT [FK_JobHistory_Employee_EmployeeID];
TRUNCATE TABLE [dbo].[Company];
TRUNCATE TABLE [dbo].[JobHistory];
TRUNCATE TABLE [dbo].[Position];
TRUNCATE TABLE [dbo].[Project];
TRUNCATE TABLE [dbo].[ProjectSkill];
TRUNCATE TABLE [dbo].[Skill];
TRUNCATE TABLE [dbo].[Employee];
ALTER TABLE [dbo].[JobHistory] WITH NOCHECK  ADD CONSTRAINT [FK_JobHistory_Company_CompanyID] FOREIGN KEY ([CompanyID] ) REFERENCES [dbo].[Company] ([CompanyID]) ON UPDATE NO ACTION  ON DELETE NO ACTION ;
ALTER TABLE [dbo].[JobHistory] WITH NOCHECK  ADD CONSTRAINT [FK_JobHistory_Position_PositionID] FOREIGN KEY ([PositionID] ) REFERENCES [dbo].[Position] ([PositionID]) ON UPDATE NO ACTION  ON DELETE NO ACTION ;
ALTER TABLE [dbo].[JobHistory] WITH NOCHECK  ADD CONSTRAINT [FK_JobHistory_Project_ProjectID] FOREIGN KEY ([ProjectID] ) REFERENCES [dbo].[Project] ([ProjectID]) ON UPDATE NO ACTION  ON DELETE NO ACTION ;
ALTER TABLE [dbo].[JobHistory] WITH NOCHECK  ADD CONSTRAINT [FK_JobHistory_Employee_EmployeeID] FOREIGN KEY ([EmployeeID] ) REFERENCES [dbo].[Employee] ([EmployeeID]) ON UPDATE NO ACTION  ON DELETE NO ACTION ;
ALTER TABLE [dbo].[ProjectSkill] WITH NOCHECK  ADD CONSTRAINT [FK_ProjectSkill_ProjectID] FOREIGN KEY ([ProjectID] ) REFERENCES [dbo].[Project] ([ProjectID]) ON UPDATE NO ACTION  ON DELETE NO ACTION ;
ALTER TABLE [dbo].[ProjectSkill] WITH NOCHECK  ADD CONSTRAINT [FK_ProjectSkill_SkillID] FOREIGN KEY ([SkillID] ) REFERENCES [dbo].[Skill] ([SkillID]) ON UPDATE NO ACTION  ON DELETE NO ACTION ;
